from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class AIConcept(BaseModel):
    """A concept extracted from learning/interview content."""

    model_config = ConfigDict(extra="ignore")

    name: str
    category: str | None = None
    explanation: str


class AIInterviewQuestion(BaseModel):
    """Interview question generated by the AI."""

    model_config = ConfigDict(extra="ignore")

    question: str
    difficulty: str = "medium"
    what_strong_answers_cover: list[str] = Field(
        default_factory=list
    )


class AIEnrichmentResponse(BaseModel):
    """
    Structured response expected from the AI enrichment stage.
    """

    model_config = ConfigDict(extra="ignore")

    summary: str
    topics: list[str] = Field(default_factory=list)
    subtopics: list[str] = Field(default_factory=list)
    concepts: list[AIConcept] = Field(default_factory=list)
    interview_questions: list[AIInterviewQuestion] = Field(
        default_factory=list
    )